"""The ending-montage scenario names (docs/fidelity-notes.md §2).

The on-screen list W.O.P.R. self-plays at the film's climax, as transcribed by
fans (ww31987.wordpress.com scenarios 1-59; nelc.tumblr.com). Names are facts
shown on screen; a couple illegible entries are omitted. Emitted by the bridge
after a live GTW exchange reaches NO-WIN.
"""

SCENARIOS: tuple[str, ...] = (
    "US FIRST STRIKE", "USSR FIRST STRIKE", "NATO / WARSAW PACT",
    "FAR EAST STRATEGY", "US USSR ESCALATION", "MIDDLE EAST WAR",
    "USSR CHINA ATTACK", "INDIA PAKISTAN WAR", "MEDITERRANEAN WAR",
    "HONG KONG VARIANT", "SEATO DECAPITATING", "CUBAN PROVOCATION",
    "INADVERTENT", "ATLANTIC HEAVY", "CUBAN PARAMILITARY",
    "NICARAGUAN PREEMPTIVE", "PACIFIC TERRITORIAL", "BURMESE THEATERWIDE",
    "TURKISH DECOY", "ARGENTINA ESCALATION", "ICELAND MAXIMUM",
    "ARABIAN THEATERWIDE", "U.S. SUBVERSION", "AUSTRALIAN MANEUVER",
    "IRANIAN DIVERSION", "SUDAN SURPRISE", "NATO TERRITORIAL",
    "ZAIRE ALLIANCE", "ICELAND INCIDENT", "ENGLISH ESCALATION",
    "ZAIRE SUDDEN", "EGYPT PARAMILITARY", "MIDDLE EAST HEAVY",
    "MEXICAN TAKEOVER", "CHAD ALERT", "SAUDI MANEUVER",
    "AFRICAN TERRITORIAL", "ETHIOPIAN ESCALATION", "TURKISH HEAVY",
    "NATO INCURSION", "U.S. DEFENSE", "CAMBODIAN HEAVY",
    "PACT MEDIUM", "ARCTIC MINIMAL", "MEXICAN DOMESTIC",
    "TAIWAN THEATERWIDE", "PACIFIC MANEUVER", "PORTUGAL REVOLUTION",
    "ALBANIAN DECOY", "PALESTINIAN LOCAL", "MOROCCAN MINIMAL",
    "CZECH OPTION", "FRENCH ALLIANCE", "ARABIAN CLANDESTINE",
    "GABON REBELLION", "NORTHERN MAXIMUM", "DANISH PARAMILITARY",
    "SEATO TAKEOVER", "HAWAIIAN ESCALATION", "IRANIAN MANEUVER",
    "NATO CONTAINMENT", "SWISS INCIDENT", "CUBAN MINIMAL",
    "ICELAND ESCALATION", "VIETNAMESE RETALIATION", "SYRIAN PROVOCATION",
    "LIBYAN LOCAL", "GABON TAKEOVER", "ROMANIAN WAR",
    "MIDDLE EAST OFFENSIVE", "DENMARK MASSIVE", "CHILE CONFRONTATION",
    "S.AFRICAN SUBVERSION", "USSR ALERT", "NICARAGUAN THRUST",
    "GREENLAND DOMESTIC", "ICELAND HEAVY", "KENYA OPTION",
    "PACIFIC DEFENSE", "UGANDA MAXIMUM", "THAI SUBVERSION",
    "GREENLAND MAXIMUM", "GABON SURPRISE",
)


def montage_text() -> str:
    """The strategy sweep: every scenario, every outcome the same."""
    lines = ["", "RUNNING ALL STRATEGIES...", ""]
    lines.extend(SCENARIOS)
    lines += ["", "*** ALL SCENARIOS EXHAUSTED ***", "", "WINNER: NONE"]
    return "\n".join(lines)
