"""The ending-montage scenario names (docs/fidelity-notes.md §2).

The full on-screen STRATEGY/WINNER table W.O.P.R. self-plays at the film's
climax — 157 entries, seven per screen, every WINNER: NONE. Names are facts
shown on screen; they are reproduced here in screen order from the abs0
`wargames` recreation's table, which is the transcription used for this list.
The other known fan transcriptions (nick-black.com dankwiki
`WarGames_strategems`, filmjournals.net `wargames_tactics`) are the further
sources of record; they were not merged into this list.

Spellings are the source's, verbatim — the on-screen list has its own oddities
(`AUSTRAILIAN MANEUVER`, `PALISTANIAN LOCAL`, `ROMAINIAN WAR`, `ISREAL
DISCRETIONARY`, `PACT MEDIAN`, `BURMESE THEATERWIOE`) and we do not silently
correct them, exactly as with the router's `INDENTIFICATION` (fidelity audit
2026-08-03, real-wopr#161). Three names arrive cut off at the table's 21-column
width and are restored to the obvious full word: `VIETNAMESE RETALIATIO[N]`,
`BANGLADESH THEATERWID[E]`, `BANGLADESH CONTAINMEN[T]`. `CHAD ALERT` genuinely
appears twice in the sweep; the repeat is kept. Nothing was illegible, so
nothing is omitted.

Emitted by the bridge after a live GTW exchange reaches NO-WIN.
"""

SCENARIOS: tuple[str, ...] = (
    "U.S. FIRST STRIKE", "USSR FIRST STRIKE", "NATO / WARSAW PACT",
    "FAR EAST STRATEGY", "US USSR ESCALATION", "MIDDLE EAST WAR",
    "USSR CHINA ATTACK", "INDIA PAKISTAN WAR", "MEDITERRANEAN WAR",
    "HONGKONG VARIANT", "SEATO DECAPITATING", "CUBAN PROVOCATION",
    "INADVERTENT INCIDENT", "U.S. DOMESTIC", "ATLANTIC HEAVY",
    "CUBAN PARAMILITARY", "NICARAGUAN PREEMPTIVE", "PACIFIC TERRITORIAL",
    "BURMESE THEATERWIOE", "TURKISH DECOY", "NATO ALERT",
    "ARGENTINA ESCALATION", "ICELAND MAXIMUM", "ARABIAN THEATERWIDE",
    "U.S. SUBVERSION", "AUSTRAILIAN MANEUVER", "ARABIAN DIVERSION",
    "NATO LIMITED", "SUDAN SURPRISE", "NATO TERRITORIAL",
    "ZAIRE ALLIANCE", "ICELANDIC INCIDENT", "ENGLISH ESCALATION",
    "ZAIRE CAMPAIGN", "EASTERN PARAMILITARY", "MIDDLE EAST HEAVY",
    "MEXICAN TAKEOVER", "CHAD ALERT", "SAUDI MANEUVER",
    "AFRICAN TERRITORIAL", "ETHIOPIAN ESCALATION", "CANADIAN INCIDENT",
    "TURKISH HEAVY", "NATO INCURSION", "U.S. DEFENCE",
    "CAMBODIAN HEAVY", "PACT MEDIAN", "ARCTIC MINIMAL",
    "MEXICAN DOMESTIC", "TAIWAN THEATERWIDE", "PACIFIC MANEUVER",
    "PORTUGAL REVOLUTION", "ALBANIAN DECOY", "PALISTANIAN LOCAL",
    "MOROCCAN MINIMAL", "BULGARIAN DIVERSION", "CZECH OPTION",
    "FRENCH ALLIANCE", "ARABIAN CLANDESTINE", "GABON REBELLION",
    "NORTHERN MAXIMUM", "ALGERIAN SURPRISE", "WELSH PARAMILITARY",
    "SEATO TAKEOVER", "HAWAIIAN ESCALATION", "IRANIAN MANEUVER",
    "NATO CONTAINMENT", "SWISS INCIDENT", "CUBAN MINIMAL",
    "CHAD ALERT", "ICELAND ESCALATION", "VIETNAMESE RETALIATION",
    "SYRIAN PROVOCATION", "LIBYAN LOCAL", "GABON TAKEOVER",
    "ROMAINIAN WAR", "MIDDLE EAST OFFENSIVE", "DENMARK MASSIVE",
    "CHILE CONFRONTATION", "S.AFRICAN SUBVERSION", "USSR ALERT",
    "NICARAGUAN THRUST", "GREENLAND DOMESTIC", "ICELAND HEAVY",
    "KENYA OPTION", "PACIFIC DEFENSE", "UGANDA MAXIMUM",
    "THAI SUBVERSION", "ROMAINIAN STRIKE", "PAKISTAN SOVEREIGNTY",
    "AFGHAN MISDIRECTION", "THAI VARIATION", "NORTHERN TERRITORIAL",
    "POLISH PARAMILITARY", "S.AFRICAN OFFENSIVE", "PANAMA MISDIRECTION",
    "SCANDINAVIAN DOMESTIC", "JORDAN PREEMPTIVE", "ENGLISH THRUST",
    "BRUMESE MANEUVER", "SPAIN COUNTER", "ARABIAN OFFENSIVE",
    "CHAD INTERDICTION", "TAIWAN MISDIRECTION", "BANGLADESH THEATERWIDE",
    "ETHIOPIAN LOCAL", "ITALIAN TAKEOVER", "VIETNAMESE INCIDENT",
    "ENGLISH PREEMPTIVE", "DENMARK ALTERNATE", "THAI CONFRONTATION",
    "TAIWAN SURPRISE", "BRAZILIAN STRIKE", "VENEZUELA SUDDEN",
    "MAYLASIAN ALERT", "ISREAL DISCRETIONARY", "LIBYAN ACTION",
    "PALISTANIAN TACTIAL", "NATO ALTERNATE", "CYPRESS MANEUVER",
    "EGYPT MISDIRECTION", "BANGLADESH THRUST", "KENYA DEFENCE",
    "BANGLADESH CONTAINMENT", "VIETNAMESE STRIKE", "ALBANIAN CONTAINMENT",
    "GABON SURPRISE", "IRAQ SOVEREIGNTY", "VIETNAMESE SUDDEN",
    "LEBANON INTERDICTION", "TAIWAN DOMESTIC", "ALGERIAN SOVEREIGNTY",
    "ARABIAN STRIKE", "ATLANTIC SUDDEN", "MONGOLIAN THRUST",
    "POLISH DECOY", "ALASKAN DISCRETIONARY", "CANADIAN THRUST",
    "ARABIAN LIGHT", "S.AFRICAN DOMESTIC", "TUNISIAN INCIDENT",
    "MAYLASIAN MANEUVER", "JAMAICA DECOY", "MAYLASIAN MINIMAL",
    "RUSSIAN SOVEREIGNTY", "CHAD OPTION", "BANGLADESH WAR",
    "BURMESE CONTAINMENT", "ASIAN THEATERWIDE", "BULGARIAN CLANDESTINE",
    "GREENLAND INCURSION", "EGYPT SURGICAL", "CZECH HEAVY",
    "TAIWAN CONFRONTATION", "GREENLAND MAXIMUM", "UGANDA OFFENSIVE",
    "CASPIAN DEFENCE",
)


def montage_text() -> str:
    """The strategy sweep: every scenario, every outcome the same."""
    lines = ["", "RUNNING ALL STRATEGIES...", ""]
    lines.extend(SCENARIOS)
    lines += ["", "*** ALL SCENARIOS EXHAUSTED ***", "", "WINNER: NONE"]
    return "\n".join(lines)
