#!/usr/bin/env python3
"""Derive the dial directory and the program index from the manifests.

`systems/<id>/harness/manifest.json` is the authority for what a system is
called and what number answers for it. Everything else that names a system is
a copy, and copies rot silently: renaming the school's dial-in id to
`school-mon` left five stale copies across three repositories and every test
suite stayed green (real-wopr#166).

    tools/gen-dial-directory.py            # rewrite the generated artifacts
    tools/gen-dial-directory.py --check    # exit 1 if they are stale

Output is committed. CI runs --check.
"""
import json
import sys
from pathlib import Path

PACK_ROOT = Path(__file__).resolve().parent.parent

KIND_BY_TOP = {"games": "game", "systems": "system", "joshua": "joshua",
               "wopr": "executive", "norad": "console"}
PROTOCOL_BY_KIND = {"game": "WOPR/1", "system": "SYSTEM/1", "joshua": "SYSTEM/1",
                    "executive": "SYSTEM/1", "console": "SYSTEM/1"}


# Every depth the pack contract puts a harness at: <cat>/harness (joshua, wopr),
# <cat>/<id>/harness (games, systems), <cat>/<id>/<interpretation>/harness
# (tictactoe). Shared with tools/build.sh and tools/test.sh by convention.
HARNESS_DEPTHS = ("harness", "*/harness", "*/*/harness")


def _manifest_paths(pack_root: Path) -> list[Path]:
    """Every program manifest, at every depth, in every category KIND_BY_TOP names.

    KIND_BY_TOP is the one place in the pack a category is spelled out, because
    naming one is a real decision — what kind of program lives there. Everything
    downstream (pack.json, tools/categories.sh, the build and test scripts)
    derives from it rather than restating it.
    """
    return [m for cat in KIND_BY_TOP for depth in HARNESS_DEPTHS
            for m in sorted(pack_root.glob(f"{cat}/{depth}/manifest.json"))]


def collect_programs(pack_root: Path) -> list[dict]:
    """The pack.json index, derived. One entry per program.

    A nested interpretations slot (games/tictactoe/{core,heuristic}) is indexed
    by its slot directory, not by each interpretation: the runtime dials
    `tictactoe` and the interpretation is chosen inside it. The slot's own
    manifests carry the slot's title (both interpretations agree); it is not
    re-derived from the id, which would mangle a hyphenated display name like
    "Tic-Tac-Toe" into "Tictactoe".
    """
    out: dict[str, dict] = {}
    for manifest in _manifest_paths(pack_root):
        data = json.loads(manifest.read_text())
        program_dir = manifest.parent.parent
        rel = program_dir.relative_to(pack_root)
        kind = KIND_BY_TOP[rel.parts[0]]
        # A nested interpretation lives two levels down (games/tictactoe/core);
        # the slot is its parent, and the slot's name is the program id.
        nested = kind == "game" and len(rel.parts) == 3
        if nested:
            rel = rel.parent
            pid = rel.parts[-1]
            if pid in out:
                continue
        else:
            pid = data["id"]
        out[pid] = {
            "id": pid,
            "kind": kind,
            # A manifest may declare its own protocol (joshua's is JOSHUA/1,
            # not the SYSTEM/1 every other program of kind "joshua" would get
            # by default — there is only the one, but the override is real).
            # Absent that, the protocol follows from the kind.
            "protocol": data.get("protocol", PROTOCOL_BY_KIND[kind]),
            "language": data["language"],
            "title": data["title"],
            "path": str(rel),
            "binary": pid,
        }
    return sorted(out.values(), key=lambda p: (p["kind"], p["id"]))


def collect_dialable(pack_root: Path) -> list[dict]:
    """Systems that answer a phone line — those whose manifest has a `number`.

    Mirrors emulator/node/app/systems.py:load_systems. Reproduced from the
    spec rather than imported: tools/ and emulator/node/ are separate modules
    of the federation.
    """
    out = []
    for manifest in sorted(pack_root.glob("systems/*/harness/manifest.json")):
        data = json.loads(manifest.read_text())
        if "number" not in data:
            continue
        out.append({"id": data["id"], "title": data["title"], "number": data["number"]})
    return sorted(out, key=lambda s: s["id"])


def render_dial_systems_ts(dialable: list[dict]) -> str:
    rows = "\n".join(
        f'  {{ systemId: {json.dumps(s["id"])}, '
        f'number: {json.dumps(s["number"])}, '
        f'title: {json.dumps(s["title"])} }},'
        for s in dialable
    )
    return f'''// GENERATED by tools/gen-dial-directory.py — do not edit.
//
// Every dialable system in the pack, straight from
// systems/<id>/harness/manifest.json. Editorial choices — display name,
// wardial label, ordering, which systems the phone book shows — live in
// sims.ts, which validates every id it names against this list.

export interface DialableSystem {{
  systemId: string;
  number: string;
  title: string;
}}

export const DIALABLE_SYSTEMS: readonly DialableSystem[] = [
{rows}
];
'''


TS_PATH = "emulator/web/home-terminal/app/dial-systems.generated.ts"


def main(argv: list[str]) -> int:
    if argv not in ([], ["--check"]):
        print(
            f"gen-dial-directory.py: unrecognised argument(s): {' '.join(argv)!r}\n"
            "usage: gen-dial-directory.py [--check]",
            file=sys.stderr,
        )
        return 2
    check = argv == ["--check"]
    pack_json = PACK_ROOT / "pack.json"
    ts_file = PACK_ROOT / TS_PATH

    data = json.loads(pack_json.read_text())
    data["programs"] = collect_programs(PACK_ROOT)
    pack_text = json.dumps(data, indent=2) + "\n"
    ts_text = render_dial_systems_ts(collect_dialable(PACK_ROOT))

    stale = []
    if pack_json.read_text() != pack_text:
        stale.append("pack.json")
    if not ts_file.exists() or ts_file.read_text() != ts_text:
        stale.append(TS_PATH)

    if check:
        for s in stale:
            print(f"stale: {s} — run tools/gen-dial-directory.py", file=sys.stderr)
        return 1 if stale else 0

    pack_json.write_text(pack_text)
    ts_file.write_text(ts_text)
    for s in stale:
        print(f"wrote {s}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
