// GENERATED by tools/gen-dial-directory.py — do not edit.
//
// Every dialable system in the pack, straight from
// systems/<id>/harness/manifest.json. Editorial choices — display name,
// wardial label, ordering, which systems the phone book shows — live in
// sims.ts, which validates every id it names against this list.

export interface DialableSystem {
  systemId: string;
  number: string;
  title: string;
}

export const DIALABLE_SYSTEMS: readonly DialableSystem[] = [
  { systemId: "airline", number: "(212) 555-0177", title: "PAN AM / PANAMAC RESERVATIONS" },
  { systemId: "pactel", number: "(311) 555-0100", title: "PACIFIC TELEPHONE" },
  { systemId: "protovision", number: "(408) 555-0163", title: "PROTOVISION" },
  { systemId: "reference", number: "(311) 555-0101", title: "REFERENCE SYSTEM" },
  { systemId: "school-mon", number: "(206) 555-0142", title: "SEATTLE SCHOOL DISTRICT" },
  { systemId: "umb", number: "(408) 555-0164", title: "UNION MARINE BANK" },
];
